[package]
name = "ebpf-analyzer"
version = "0.1.0"
edition = "2021"
description = "More than an eBPF verifier"
repository = "https://githubcom/yesh0/ebpf-analyzer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
