[workspace]
members = [
    "analyzer",
    "crates/atomic",
    "crates/consts",
    "crates/macros",
    "crates/lldump",
    "crates/bpfasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://githubcom/yesh0/ebpf-analyzer"
license = "MIT"
