[workspace]
members = [
    "analyzer",
    "crate/atomic",
    "crate/consts",
    "crate/macros",
    "crate/lldump",
    "crate/bpfasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://githubcom/yesh0/ebpf-analyzer"
license = "MIT"
