[package]
name = "ebpf-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
ebpf-consts = { path = "../consts" }
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = "1.0.102"

[lib]
proc-macro = true
