[package]
name = "opcode-macros"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = "1.0.102"

[dev-dependencies]
ebpf-consts = { path = "../consts" }

[lib]
proc-macro = true
