name: Test Coverage

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Install bpf_conformance deps
        run: sudo apt install cmake libbpf-dev libboost-all-dev
      - name: Generate conformance tests
        run: make -C analyzer conformance-gen
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --all --all-features -- -A stable-features
      - name: Run tests
        run: cargo test --workspace --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
      - name: Gather Coverage
        uses: actions-rs/grcov@v0.1.5
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          verbose: true
          # not required for public repos, but good-to-have to escape GitHub rate limit
          token: ${{ secrets.CODECOV_TOKEN }}
